# Generated by Django 3.1.7 on 2021-03-11 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveIntegerField(verbose_name='Лайки')),
                ('value', models.PositiveIntegerField(verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('ND', 'Not defined')], default=('ND', 'Not defined'), max_length=2, verbose_name='Пол')),
                ('user_country', models.CharField(max_length=100, verbose_name='Страна')),
                ('user_city', models.CharField(max_length=100, verbose_name='Город')),
                ('user_description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('user_image', models.ImageField(upload_to='user_photos/', verbose_name='Изображение')),
                ('date_register', models.DateField(default=datetime.date.today, verbose_name='Дата регистрации')),
                ('last_online', models.DateTimeField(verbose_name='Заходил последний раз')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент')),
                ('user_url', models.SlugField(max_length=160, unique=True)),
                ('coef_range_min', models.FloatField(verbose_name='Нижняя граница поиска')),
                ('coef_range_max', models.FloatField(verbose_name='Верхняя граница поиска')),
                ('status', models.CharField(choices=[('ON', 'Online'), ('OFF', 'Offline'), ('G', 'Gone'), ('S', 'Sleep')], max_length=3, verbose_name='Статус')),
                ('display_status', models.BooleanField(default=True)),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='heartbits_app.userrating')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
