# Generated by Django 3.1.7 on 2021-03-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0003_auto_20210312_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbits_app.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbits_app.userrating', verbose_name='Рейтинг пользователя'),
        ),
    ]
