# Generated by Django 3.1.7 on 2021-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0004_auto_20210312_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_result',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
