# Generated by Django 3.1.7 on 2021-03-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0005_auto_20210312_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(default=None, null=True, to='heartbits_app.Answer', verbose_name='Ответы'),
        ),
    ]
