# Generated by Django 3.1.7 on 2021-03-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0006_auto_20210312_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coef_range_max',
            field=models.FloatField(default=0.0, verbose_name='Верхняя граница поиска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coef_range_min',
            field=models.FloatField(default=0.0, verbose_name='Нижняя граница поиска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coefficient',
            field=models.FloatField(default=0.0, verbose_name='Коэффициент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_register',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заходил последний раз'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbits_app.userrating', verbose_name='Рейтинг пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbits_app.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='user_photos/', verbose_name='Изображение'),
        ),
    ]
