# Generated by Django 3.1.7 on 2021-03-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0007_auto_20210312_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_register',
            field=models.DateField(auto_created=True, verbose_name='Дата регистрации'),
        ),
    ]
