# Generated by Django 3.1.7 on 2021-03-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0008_auto_20210312_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='like',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='value',
        ),
        migrations.AddField(
            model_name='userrating',
            name='id_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='heartbits_app.user', verbose_name='Кто поставил'),
        ),
    ]
