# Generated by Django 3.1.7 on 2021-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0009_auto_20210312_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='id_user',
            new_name='id_user_liked',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_register',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
