# Generated by Django 3.1.7 on 2021-03-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0010_auto_20210312_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbits_app.user', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='heartbits_app.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='id_user_liked',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_liked', to='heartbits_app.user', verbose_name='Кто поставил'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'id_user_liked')},
        ),
    ]
