# Generated by Django 3.1.7 on 2021-03-15 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0012_auto_20210313_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='День рождения'),
        ),
    ]
