# Generated by Django 3.1.7 on 2021-03-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0014_auto_20210315_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_register',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_online',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Заходил последний раз'),
        ),
    ]
