# Generated by Django 3.1.7 on 2021-03-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0016_auto_20210321_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_max_age',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='Максимальный возраст партнера'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('ND', 'Not defined')], default=('ND', 'Not defined'), max_length=2, verbose_name='Пол партнера'),
        ),
    ]
