# Generated by Django 3.1.7 on 2021-03-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0018_auto_20210324_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес'),
        ),
    ]
