# Generated by Django 3.1.7 on 2021-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0019_answer_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_result',
        ),
        migrations.AddField(
            model_name='test',
            name='result',
            field=models.JSONField(null=True, verbose_name='Результаты теста'),
        ),
    ]
