# Generated by Django 3.2 on 2021-05-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbits_app', '0022_auto_20210506_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coef_range_max',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coef_range_min',
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
